local types = include("diject.quest_guider.types")

return {
    [types.requirementType.CustomActor] = { str = "Talk to @objectObj.name@", priority = -1000 },
    [types.requirementType.Item] = { str = "\"@variableObj.name@\" item count #operator# #value# for @objectObj.name@", },
    [types.requirementType.CustomDisposition] = { str = "Disposition #operator# #value#", priority = -1001 },
    [types.requirementType.PreviousDialogChoice] = { str = "#value#nd dialogue selected", priority = -1001 },
    [types.requirementType.CustomPCFaction] = { str = "@valueObj.name@ faction", },
    [types.requirementType.Dead] = { str = "@variableObj.name@'s death count #operator# #value#", },
    [types.requirementType.CustomActorCell] = { str = "Find someone in @valueObj.name@", priority = -1000 },
    [types.requirementType.NotActorID] = { str = "Someone not @variableObj.name@", priority = -1001 },
    [types.requirementType.CustomPCRank] = { str = "@variableObj:getRankName(value)@ rank for @variableObj.name@", },
    [types.requirementType.CustomActorGender] = { str = "Someone's gender is #operator# @value == 0 and \"male\" or \"female\"@", priority = -1001 },
    [types.requirementType.PlayerLevel] = { str = "Player level #operator# #value#", },
    [types.requirementType.CustomActorFaction] = { str = "Someone in @valueObj.name@ faction", priority = -1001 },
    [types.requirementType.NotActorRace] = { str = "Someone's race not @variableObj.name@", priority = -1001 },
    [types.requirementType.Journal] = { str = "Stage of \"#variableQuestName#\" quest #operator# #value#", },
    [types.requirementType.CustomLocal] = { str = "Local variable @variable@ for @objectObj.name@ #operator# #value#", },
    [types.requirementType.CustomCurrentAIPackage] = { str = "AI action in action", },
    [types.requirementType.CustomGlobal] = { str = "Global variable @variable@ #operator# #value#", },
    [types.requirementType.CustomDistance] = { str = "Distance to @variableObj.name@ #operator# #value#", },
    [types.requirementType.CustomActorClass] = { str = "Someone's class #operator# #value#", priority = -1001 },
    [types.requirementType.NPCSameFactionAsPlayer] = { str = "@objectObj.name@ faction @value == 0 and \"not\" or \"\" #operator# player faction@", },
    [types.requirementType.NPCTalkedToPlayer] = { str = "@objectObj.name@ talked to player @value == 0 and \"before\" or \"\"@", },
    [types.requirementType.CustomSkill] = { str = "@tes3.skillName[skill]@ of @objectObj.name@ #operator# #value#", },
    [types.requirementType.PlayerGender] = { str = "Player gender #operator# @value == 0 and \"male\" or \"female\"@", },
    [types.requirementType.CustomAIPackageDone] = { str = "AI action done", },
    [types.requirementType.NPCSameGenderAsPlayer] = { str = "@objectObj.name@ has@operator + value ~= 49 and \"n't\" or \"\"@ same gender as player", },
    [types.requirementType.CustomAttribute] = { str = "@tes3.attributeName[skill]@ of @objectObj.name@ #operator# #value#", },
    [types.requirementType.PlayerReputation] = { str = "Player reputation #operator# #value#", },
    [types.requirementType.RankRequirement] = { str = "@variableObj:getRankName(value)@ rank for @variableObj.name@", },
    [types.requirementType.PlayerIsVampire] = { str = "Player is@operator + value ~= 49 and \"n't\" or \"\"@ vampire", },
    [types.requirementType.NPCIsAlarmed] = { str = "@objectObj.name@ is@operator + value ~= 49 and \"n't\" or \"\"@ alarmed", },
    [types.requirementType.NPCAttacked] = { str = "@objectObj.name@ is@operator + value ~= 49 and \"n't\" or \"\"@ attacked", },
    [types.requirementType.PlayerIsDetected] = { str = "Player is@operator + value ~= 49 and \"n't\" or \"\"@ detected", },
    [types.requirementType.CustomPCSleep] = { str = "Player is@operator + value ~= 49 and \"n't\" or \"\"@ asleep", },
}
-- type = "SCR",
-- type = "CST",
-- type = "EFF",
-- type = "SPL",

-- req parser changes
-- type = "ODT",
-- type = "OAT",
-- type = "NLC",
-- type = "BLD",
-- type = "OKO",
-- type = "CND",

-- type = "OPA", - wrong value